title: HPは自分で作る
email: saitomako@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  このサイトでは、ホームページ作成サービス「クローバPAGE」を使って
  専門知識がなくても簡単にホームページを作成する方法を解説しております。
baseurl: "/hpbyself/" # the subpath of your site, e.g. /blog
url: "https://saitomako.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
