title: ホームページは自分で作れ！
author: GitHub User
email: saitomako@gmail.com
description: > # this means to ignore newlines untile "twitter_username:"
  還暦過ぎのわたしでもホームページ作れました

show_excerpts: true # set to true to show excerpts on the homepage
excerpt_separator: <!--more-->

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
